version: '1'
services:
    mysql:
        image: mysql:8.0.31
        environment:
            MYSQL_ROOT_PASSWORD: 11111111
            MYSQL_PASSWORD: 11111111
            MYSQL_DATABASE: mydatabase
            MYSQL_TEST_DATABASE: testdatabase
        ports:
            - 3306:3306
        healthcheck:
            test: ['CMD', 'mysqladmin', 'ping', '-h', 'localhost']
            interval: 3s
            timeout: 5s
            retries: 10

    app:
        build:
            context: .
            dockerfile: ./DockerFile
        environment:
            PORT: 3000
            DB_CONNECTION: mysql://root:11111111@mysql:3306/mydatabase
            JWT_SECRET_KEY: jwtSecretKey
            JWT_EXPIRE_DATE: 2h
            SALT: 10
        ports:
            - 80:3000

        depends_on:
            mysql:
                condition: service_healthy
